name: example-environment
channels:
  - conda-forge
  - pytorch
  - anaconda
dependencies:
  - python
  - numpy
  - cudatoolkit=10.2
  - pandas
  - scikit-learn 
  - matplotlib #==3.3.2
  - pytorch
  - geopy
  - ipython
  - pyproj #>=3.0
  - rasterstats
  - torchvision #==0.9.0 # this line added
  - pip
  - pip:
    - torch
    - pillow #==7.2.0
    - pytz #==2020.4
    - scikit-image #==0.19.3
    #- affine==1.3.1

    #- pyproj==1.9.5.1
    #- geopy==2.0.0
    #- ipython==7.8.11
    