---
title: "0805"
author: "Xinran Miao"
date: "8/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("readr");library(dplyr);library(superheat);library(plyr);library(ggplot2)
source('function_ensemble.R')
base_dir = './results/'
ifelse(!dir.exists(base_dir), dir.create(base_dir), FALSE)
```

```{r}
cnames <- c("Value","Income","Age", "Room","Bedroom","Population", "Households","Latitude","Longitude")
housing <- read_table("cadata.txt", col_names = cnames) %>%
  mutate(
    AvgRooms = Room / Households,
    AvgBedrooms = Bedroom / Households,
    Value = Value / 1000
  ) %>%
  select(-Room, -Bedroom)
```

```{r}
seed = 0
K = 3
output_dir = paste0(base_dir,'seed',seed,'_K',K,'/','seed',seed,'_K',K)
dir.create(paste0(base_dir,'seed',seed,'_K',K,'/'))
l = source_split(df = housing, 
             idx_target = which((housing$Longitude > -118)&
                                  (housing$Longitude < -116) &
                                  (housing$Latitude > 33) &
                                  (housing$Latitude < 35)),
             target_fraction = NULL,
             n_cluster = 3,
             seed = seed, 
             val_fraction = 0.5,
             output_dir = output_dir, 
             plotting = TRUE, 
             data_type = 'California'
)
Source = l$Source; Validation = l$Validation; Test = l$Test
#write.csv(Source,paste0(output_dir,'Source.csv'),row.names = FALSE)
#write.csv(Validation,paste0(output_dir,'Validation.csv'),row.names = FALSE)
#write.csv(Test,paste0(output_dir,'Test.csv'),row.names = FALSE)
dat = generate_dat(l$Source, l$Test, l$Validation,
                          n_training = 200,
                   n = 1000,
                   para =rep(1,K),
                   mod = 'lm',
                   output_dir = output_dir,
                   additional_dir = '')   


# Plot the summary statistic -----
s = rep(1,100)
for (i in 1:100) {
  s[i] = w2stat(dat[,c(2:ncol(dat),1)], n_cluster = K,num_stats = i)
}
jpeg(paste0(output_dir,'_w2stat.jpeg'));plot(1:100,s,xlab = 'Number of Weight Combinations',ylab = 'Summary Statistic',main = paste0(n_cluster,' clusters'));lines(1:100,s);dev.off()

# Ensemble plot
ensemble(dat,output_dir = output_dir,
         n_cluster = K,additional_dir = '')


```
